spring:
  application:
    name: outbox
  main:
    allow-bean-definition-overriding: true
#  datasource:
#    url: ${DATABASE_URL}
#    username: ${DATABASE_USERNAME}
#    password: ${DATABASE_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: false
#  sql:
#    init:
#      mode: never
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_URI}
      bindings:
        debeziumEventConsumer-in-0:
          destination: ${DEBEZIUM_DESTINATION}
          group: 1
          content-type: application/json
#  kafka:
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json:
#          trusted.packages: com.ecommerce.outbox
#          value:
#            default.type: com.ecommerce.outbox.events.OutboxEvent
